### ISSUE TITLE
The "dqc-module.h" didn't under the ns3 file, where was it?

### ISSUE THREAD

**Issue by YangYangGirl** [SoonyangZhang/DrainQueueCongestion#1]

**Comment by SoonyangZhang** [comment]
Automatically generated by ns3!  Each model file will generate a xx-module.h file after compiling. It seems that you are not quite famlial with ns3.

**Comment by YangYangGirl** [comment]
谢谢您的回复，我确实是一个新手。
在成功运行过ns3的example后，我将原有的scratch文件替换成了您的，在./waf configure 指令后，输入./waf，但是出现了如下错误。
![image](https://user-images.githubusercontent.com/32426369/72338105-c00ea600-36fe-11ea-8036-b122824b9493.png)

![image](https://user-images.githubusercontent.com/32426369/72337812-2b0bad00-36fe-11ea-9612-d6cce060749a.png)
我很疑惑缺少的是哪一步。

**Comment by YangYangGirl** [comment]
可以请问一下，具体是怎么compile的呢？

**Comment by SoonyangZhang** [comment]
QQ：865678017
