### ISSUE TITLE
请问如何查看代码的运行结果，以及将其可视化，就像在本项目的readme文档中的那样？

### ISSUE THREAD

**Issue by Qfccse** [SoonyangZhang/DrainQueueCongestion#12]

**Comment by SoonyangZhang** [comment]
运行之后，一个trace文件夹，数据记录在文本中，调用gnuplot画图。

**Comment by Qfccse** [comment]
谢谢，请问怎么获得丢包率之类的数据呢？我发现不管有没有设置lo参数，根据获得的owd文件的最后一列计算得到的都是0.33的丢包率

**Comment by SoonyangZhang** [comment]
拥塞控制算法必然导致链路拥塞。比如，cubic算法，在没有丢包的时候，会一直增加拥塞窗口，最终导致数据包在网络中积压，超出AQM算法的阈值，不就有丢包了吗。lo参数设置的网卡的随机丢包。

**Comment by SoonyangZhang** [comment]
owd文件中存在包序号，根据缺失的数据包序号，大致可以统计出丢包率。

**Comment by Qfccse** [comment]
我来试试，多谢
