### ISSUE TITLE
环境配置问题

### ISSUE THREAD

**Issue by O-Ofdm** [SoonyangZhang/DrainQueueCongestion#14]
你好，在执行您的这段代码 trace1.Log(log,DqcTraceEnable::E_DQC_OWD|DqcTraceEnable::E_DQC_BW|DqcTraceEnable::E_DQC_GOODPUT);
出现了这个错误bash: syntax error near unexpected token `log,DqcTraceEnable::E_DQC_OWD'。
请问您能给出什么解决方法吗，万分感谢！

**Comment by SoonyangZhang** [comment]
这个库，别人运行过。不知道你的错误出在哪里。
我在公司拉磨，也没空帮你看。
那就试试这个吧：https://github.com/SoonyangZhang/quic-on-ns3

**Comment by O-Ofdm** [comment]
您好，我在执行下面的语句时，执行到./waf configure这一句时，出现了错误，“bash: ./waf: No such file or directory”。
下图是执行结果。想问问您在执行过程中有遇到吗？该怎么解决呢。
周末打扰您，万分歉意。祝生活工作顺利！











------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SoonyangZhang/DrainQueueCongestion"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月3日(星期一) 晚上9:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SoonyangZhang/DrainQueueCongestion] 环境配置问题 (Issue #14)





 
这个库，别人运行过。不知道你的错误出在哪里。
 我在公司拉磨，也没空帮你看。
 那就试试这个吧：https://github.com/SoonyangZhang/quic-on-ns3

**Comment by SoonyangZhang** [comment]
你成功编译过ns3吗？这是ns3的编译问题啊！

**Comment by O-Ofdm** [comment]
再次打扰，真是不好意思。我在执行下边run&nbsp;example&nbsp;时报了下边两个错误，没有出现trace文件夹。想请教下您，我是哪里出现了问题，该如何解决。祝工作生活顺利。


***@***.***:/home/opensourcesdr/Desktop/ns3/ns-allinone-3.37/ns-3.37# ./ns3 run "scratch/quic-main --cc=bbr"
Traceback (most recent call last):
&nbsp; File "./ns3", line 1546, in <module&gt;
&nbsp; &nbsp; main()
&nbsp; File "./ns3", line 1327, in main
&nbsp; &nbsp; refuse_run_as_root()
&nbsp; File "./ns3", line 1320, in refuse_run_as_root
&nbsp; &nbsp; raise Exception("Refusing to run as root. --enable-sudo will request your password when needed")
Exception: Refusing to run as root. --enable-sudo will request your password when needed





***@***.***:/home/opensourcesdr/Desktop/ns3/ns-allinone-3.37/ns-3.37# ./ns3 run "scratch/quic-main --cc=cubic"&nbsp;
Traceback (most recent call last):
&nbsp; File "./ns3", line 1546, in <module&gt;
&nbsp; &nbsp; main()
&nbsp; File "./ns3", line 1327, in main
&nbsp; &nbsp; refuse_run_as_root()
&nbsp; File "./ns3", line 1320, in refuse_run_as_root
&nbsp; &nbsp; raise Exception("Refusing to run as root. --enable-sudo will request your password when needed")
Exception: Refusing to run as root. --enable-sudo will request your password when needed

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SoonyangZhang/DrainQueueCongestion"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月8日(星期六) 中午11:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SoonyangZhang/DrainQueueCongestion] 环境配置问题 (Issue #14)





 
你成功编译过ns3吗？这是ns3的编译问题啊！

**Comment by SoonyangZhang** [comment]
https://blog.csdn.net/u010643777/article/details/106761440
自己创建一个 traces文件夹，博客里面有说明。
我在公司拉磨，回复不及时，抱歉。

**Comment by O-Ofdm** [comment]
我们成功执行了./waf --run "scratch/bbr-var-eva-3.30 --it=1 --cc=bbr" 这段代码，您上次回复我的csdn博客中，没有别的.cc文件执行代码。请问别的.cc文件如何执行。深夜打扰，万分抱歉。祝生活工作顺利！



&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ---三个第一次接触ns3的菜鸟
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SoonyangZhang/DrainQueueCongestion"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月11日(星期二) 晚上9:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SoonyangZhang/DrainQueueCongestion] 环境配置问题 (Issue #14)





 
https://blog.csdn.net/u010643777/article/details/106761440
 自己创建一个 traces文件夹，博客里面有说明。
 我在公司拉磨，回复不及时，抱歉。

**Comment by SoonyangZhang** [comment]
先研究明白一个，再说其他的。都是配置参数，一样的套路。
