### ISSUE TITLE
building error

### ISSUE THREAD

**Issue by yilengyanhua** [SoonyangZhang/DrainQueueCongestion#2]
It seems the recv isn't defined in your code. Maybe the recv should be ret?
The code comes from /dqc/model/thirdparty/src/proto_socket.cc
int UdpSocket::RecvFrom(char*buf,size_t size,SocketAddress &peer){
    int ret=0;
    su_addr dst;
    ret=su_udp_recv(fd_,&dst,(void*)buf,(uint32_t)size,0);
    if(recv>=0){
        char ip[40];
        uint16_t port;
        su_addr_to_iport(&dst,ip,40,&port);
        std::string host(ip,strlen(ip));
        peer=SocketAddress(host,port);
    }
    return ret;
}

**Comment by SoonyangZhang** [comment]
The code can be running on ns3 platform.  Do you build it with wscript in ns3?  Plase give me the detail error during the builiding of ns3 module.

**Comment by SoonyangZhang** [comment]
It seems you build with cmake with an early version. In early version, I intend to make this  code useable by calling socket in operting system. But I give up that goal finally. Please download the newest code and test in on ns3. You have my word it can be running on ns3. But to send packet over socket may need extra effort. I am in my fifth year of phd candidate and I have other more urgent work to do. It seems you are interesting to the performance of multipath BBR. The original paper is easily accessed and I have tested it no ns3. Why not implement it mptcp. Only half of a day, such work can be done!

**Comment by yilengyanhua** [comment]
The detail of error information can be seen as follows:
../src/dqc/model/thirdparty/src/proto_socket.cc:26:12: error: ordered comparison between pointer and zero ('ssize_t (*)(int, void *, size_t, int)' (aka 'long (*)(int, void *, unsigned long, int)') and 'int')

**Comment by SoonyangZhang** [comment]
qq：865678017
