### ISSUE TITLE
ns3编译问题

### ISSUE THREAD

**Issue by adcen0107** [SoonyangZhang/DrainQueueCongestion#4]
我的虚拟机是18.04，使用ns-3.30.1，运行这里的测试时找不到头文件的dqc-module.h，我在机器上全局搜索，也确实没有这个文件，请问这是怎么回事呢？
root@rw-vm:/home/workspace/ns-allinone-3.30.1/ns-3.30.1# ./waf --run "scratch/dqc-test --it=1 --cc=bbr"  
Waf: Entering directory `/home/workspace/ns-allinone-3.30.1/ns-3.30.1/build'
[2683/2745] Compiling scratch/dqc-test.cc
[2685/2745] Linking build/scratch/subdir/subdir
../scratch/dqc-test.cc:9:10: fatal error: ns3/dqc-module.h: No such file or directory
 #include "ns3/dqc-module.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by SoonyangZhang** [comment]
dqc-module.h是ns3自动生成的。先编译库，再把测试文件放进scratch。用ns-3.30，你测试parking-lot.cc这个。其他的文件需要少做修改，主要是traffic control 模块。明白？
made some  minor change to quic_bbr2_probe_rtt.h：
```
class QUIC_EXPORT_PRIVATE Bbr2ProbeRttMode final : public Bbr2ModeBase {
 public:
  //using Bbr2ModeBase::Bbr2ModeBase;
  Bbr2ProbeRttMode(const Bbr2Sender* sender,
                                 Bbr2NetworkModel* model)
    : Bbr2ModeBase(sender, model){}
```
