### ISSUE TITLE
如何提取CC算法中的一些数据如RTT，cwnd之类的？

### ISSUE THREAD

**Issue by BobAnkh** [SoonyangZhang/DrainQueueCongestion#5]
您好，非常感谢您这个集合了众多CC的非常棒的项目，我希望利用您的项目来进行一些仿真实验，但是我在使用ns3方面是一个新手，而且您的代码量非常庞大，一时没有理清其内在逻辑。所以我冒昧询问一下，如果我希望比如提取bbr算法(src/dqc/model/thirdparty/congestion/proto_bbr_sender.cc)中的RTT，BW，cwnd等数据用来分析，我该怎么做呢？

我看到您的dqc_trace和dqc_sender中提供了一些记录如BW等的接口，但是没有明白其他数据应该如何获取？以及不太明白如proto_bbr_sender中的DebugState应该如何使用（这个里面看起来提供了很多需要的数据）？proto_bbr_sender中好像也提供了CalculateCongestionWindow类似这样的函数，但是我没有找到在顶层是怎么一路调用到这个函数的，以及这个函数的结果应该如果获取下来？

感谢您百忙之中能够阅读我的issue，非常感谢如果您能够不吝赐教！

**Comment by SoonyangZhang** [comment]
Here is an example on how I get sending rate (https://github.com/SoonyangZhang/DrainQueueCongestion/blob/master/dqc/model/dqc_sender.cc#L164):
```
void DqcSender::SendToNetwork(Ptr<Packet> p){
	uint32_t ms=Simulator::Now().GetMilliSeconds();
	m_lastSentTs=ms;
	TimeTag tag;
    tag.SetSentTime (ms);
	p->AddPacketTag (tag);
	if(!m_traceBwCb.IsNull()){
		QuicBandwidth send_bw=m_connection.EstimatedBandwidth();
		m_traceBwCb((int32_t)send_bw.ToKBitsPerSecond());
		//NS_LOG_INFO("bw "<<std::to_string((int32_t)send_bw.ToKBitsPerSecond()));
	}
    m_socket->SendTo(p,0,InetSocketAddress{m_peerIp,m_peerPort});
}
```
Similar, you can add function to get congestion window on ProtoCon and SendAlgorithmInterface.
[ProtoCon](https://github.com/SoonyangZhang/DrainQueueCongestion/blob/master/dqc/model/thirdparty/include/proto_con.h#L96)--SendPacketManager--[SendAlgorithmInterface](https://github.com/SoonyangZhang/DrainQueueCongestion/blob/master/dqc/model/thirdparty/congestion/proto_send_algorithm_interface.h#L71)

**Comment by BobAnkh** [comment]
Ok, thank you for your help! I will try to get the data with your instructions.
