### ISSUE TITLE
程序在运行过程中出现con time out是存在链路错误了吗？

### ISSUE THREAD

**Issue by zzuchen** [SoonyangZhang/DrainQueueCongestion#8]
您好，在程序运行过程中，出现
![1646464615(1)](https://user-images.githubusercontent.com/58057154/156872959-c99152b0-281e-4498-ad0e-d566daf432d9.png)
是链路出错了吗？

**Comment by SoonyangZhang** [comment]
代码输出提示，凑合能跑。这个代码是参考quic实现的，不太完整，重传机制做的不好。有个更好的版本：https://github.com/SoonyangZhang/quic-on-ns3。dqc中的相关拥塞控制算法很容易移植到quic on ns3，你可以试试。

**Comment by zzuchen** [comment]
> [代码输出提示，凑合能跑](https://github.com/SoonyangZhang/quic-on-ns3%E3%80%82dqc%E4%B8%AD%E7%9A%84%E7%9B%B8%E5%85%B3%E6%8B%A5%E5%A1%9E%E6%8E%A7%E5%88%B6%E7%AE%97%E6%B3%95%E5%BE%88%E5%AE%B9%E6%98%93%E7%A7%BB%E6%A4%8D%E5%88%B0quic)。这个quic实现的代码完整情况，是参考了不好的重传机制。[。dqc中的相关支持塞控制算法很容易移植到](https://github.com/SoonyangZhang/quic-on-ns3%E3%80%82dqc%E4%B8%AD%E7%9A%84%E7%9B%B8%E5%85%B3%E6%8B%A5%E5%A1%9E%E6%8E%A7%E5%88%B6%E7%AE%97%E6%B3%95%E5%BE%88%E5%AE%B9%E6%98%93%E7%A7%BB%E6%A4%8D%E5%88%B0quic)ns3上，你可以试试。
好的，谢谢啦！
